### PR TITLE
Changes to app.py and form.html

### PR DESCRIPTION
**Pull request by heidage**
I used Jinja in the form.html to allow me to get the district and state names and make it into a list. I used jQuery in the form .html to  remove the selected source district in the destination district

### CODE REVIEW

**Comment by abhishek-bodapati** [comment]
The PR was very good.. I have just provided some comment to make sure the code handles all the corner cases!
- All the districts of every state are displaying in the districts drop-down list.
- Make sure only the selected state's districts are displayed.
- Make sure even the districts' drop-down list should show nothing until the state is selected.

**Comment by heidage** [comment]
Hello i am done. I have successfully added the changes. Would u like to check it? Do i carry out the same procedure and do another pull request after committing my changes?

**Comment by abhishek-bodapati** [comment]
> Hello i am done. I have successfully added the changes. Would u like to check it? Do i carry out the same procedure and do another pull request after committing my changes?

Please commit and push your changes so that I can have a look!

**Comment by heidage** [comment]
I have committed the changes. Please have a look:)

**Review by abhishek-bodapati — APPROVED** [review]
Selected source district is also getting displayed in destination district. But it's ok!
Thanks for your contribution!

**Comment by heidage** [comment]
I am so sorry about that..do u have any other projects that u would require help in?

**Pull request merged**
